version: '3'
services:
    web:
        image: webdevops/php-apache-dev:7.3
        container_name: web
        restart: always
        user: application
        environment:
          - WEB_ALIAS_DOMAIN=local.domain.com
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=-1
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=1000M
          - PHP_UPLOAD_MAX_FILESIZE=-1
        volumes:
          - "./:/app:cached"
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
        links:
          - mysql
    mysql:
        image: mariadb:10
        container_name: magentomysql
        restart: always
        ports:
          - "3307:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        volumes:
          - db-data:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - PMA_USER=root
          - PMA_PASSWORD=root
        ports:
          - "8028:80"
        links:
          - mysql:db
        depends_on:
          - mysql
volumes:
    db-data:
        external: false